[workspace]
members = [
    "node",
    "runtime",
    "pallets/primitives",
    "pallets/token",
    "pallets/dex",
    "pallets/currency",
    "pallets/nft",
    "pallets/commodity",
    "pallets/tao",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
